"""BASELINE_CAPABILITIES.txt must be stable between identical runs.

It is regenerated by the capability suite and tracked on purpose (it is the
acceptance baseline), but it recorded each PASSing check's incidental output —
pytest tmpdir ids and live weather readings:

    PASS  create_file   Written 2 bytes to /tmp/pytest-of-jeevan/pytest-6/...
    PASS  weather_fetch Hyderabad: Sunny, 35C (feels 27C), Humidity 35%...

so it changed on every run and `git status` was never clean. A file that is
always dirty is a file whose real changes nobody notices.

The table's contract is which capabilities work. Detail belongs on the rows
where it is diagnostic — the failures.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from test_capabilities import _snapshot_lines  # noqa: E402


def test_passing_rows_carry_no_volatile_detail():
    lines = _snapshot_lines([("create_file", "PASS",
                              "Written 2 bytes to /tmp/pytest-of-x/pytest-138/t")])
    body = "\n".join(lines)
    assert "pytest-138" not in body
    assert "create_file" in body
    assert "PASS" in body


def test_failing_rows_keep_their_detail():
    lines = _snapshot_lines([("git_status", "FAIL", "fatal: not a git repository")])
    body = "\n".join(lines)
    assert "fatal: not a git repository" in body


def test_skipped_rows_keep_their_reason():
    lines = _snapshot_lines([("webcam", "SKIP", "no camera present")])
    assert "no camera present" in "\n".join(lines)


def test_identical_results_produce_identical_output():
    r = [("a", "PASS", "x"), ("b", "FAIL", "boom")]
    assert _snapshot_lines(r) == _snapshot_lines(list(r))


def test_pass_detail_changing_does_not_change_the_file():
    # The whole point: a different tmpdir or a different temperature must not
    # show up as a diff.
    a = _snapshot_lines([("weather_fetch", "PASS", "Hyderabad: Sunny, 35C")])
    b = _snapshot_lines([("weather_fetch", "PASS", "Hyderabad: Rain, 21C")])
    assert a == b


def test_counts_are_still_reported():
    lines = _snapshot_lines([("a", "PASS", ""), ("b", "FAIL", "x"), ("c", "SKIP", "y")])
    header = "\n".join(lines)
    assert "PASS=1" in header and "FAIL=1" in header and "SKIP=1" in header
    assert "TOTAL=3" in header


def test_capability_names_are_preserved_in_order():
    lines = _snapshot_lines([("first", "PASS", ""), ("second", "PASS", "")])
    body = "\n".join(lines)
    assert body.index("first") < body.index("second")
